version: "3"
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile-jupyter.yml
    command: jupyter notebook --port=8888 --no-browser --ip=0.0.0.0 --allow-root
    volumes:
      - .:/usr/src/app
    ports:
      - "8888:8888"
      
